name: localhost

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  CheckSyntax:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Checkear sintaxis de modelo
        run: php -l modelos/usuarioModelo.class.php

  CheckVarDump:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Checkear si hay var_dump
        run: grep -q var_dump modelos/usuarioModelo.class.php && exit 1 || true

      - name: Checkear si hay print_r
        run: grep -q print_r modelos/usuarioModelo.class.php && exit 1 || true
        
